# -*- coding: utf-8 -*-
"""IoT_Food_Detection_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztAmKQ13uQyKz1mfYUcG6DPsQMBY0CCV
"""

!pip install paho-mqtt opencv-python scikit-learn numpy pandas

from google.colab import output
from IPython.display import display, Javascript
import base64
import io
from PIL import Image
import numpy as np

def capture_image():
    display(Javascript("""
    async function captureImage() {
        const div = document.createElement('div');
        const video = document.createElement('video');
        const button = document.createElement('button');

        button.textContent = '📸 Capture Image';
        div.appendChild(video);
        div.appendChild(button);
        document.body.appendChild(div);

        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        video.srcObject = stream;
        await video.play();

        await new Promise(resolve => button.onclick = resolve);

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        stream.getTracks().forEach(track => track.stop());
        div.remove();

        return canvas.toDataURL('image/jpeg');
    }
    """))

    return output.eval_js('captureImage()')

# Capture image
image_data = capture_image()

# Convert base64 to image
image_bytes = base64.b64decode(image_data.split(',')[1])
image = Image.open(io.BytesIO(image_bytes))

# Display image
display(image)

image_np = np.array(image)
print(image_np.shape)

binary = base64.b64decode(image_data.split(',')[1])
image = Image.open(io.BytesIO(binary))
image_np = np.array(image)

image_np.shape

r = np.mean(image_np[:,:,0])
g = np.mean(image_np[:,:,1])
b = np.mean(image_np[:,:,2])

print("R:", r, "G:", g, "B:", b)

import random

def simulate_sensors():
    return {
        "weight": round(random.uniform(100, 500), 2),      # grams
        "temperature": round(random.uniform(25, 60), 2),   # °C
        "moisture": round(random.uniform(20, 90), 2),      # %
        "gas": round(random.uniform(100, 500), 2)          # smell intensity
    }

sensors = simulate_sensors()
sensors

import pandas as pd

foods = ["RICE", "DAL", "CURRY", "MILK", "OIL"]
data = []

for food in foods:
    for _ in range(50):
        data.append([
            random.uniform(100, 500),
            random.uniform(25, 60),
            random.uniform(20, 90),
            random.uniform(50, 255),
            random.uniform(50, 255),
            random.uniform(50, 255),
            random.uniform(100, 500),
            food
        ])

df = pd.DataFrame(data, columns=[
    "weight","temperature","moisture","r","g","b","gas","label"
])

df.head()

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = df.drop("label", axis=1)
y = df["label"]

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

model = RandomForestClassifier(n_estimators=200)
model.fit(X, y_encoded)

import paho.mqtt.client as mqtt
import json

client = mqtt.Client()
client.connect("broker.hivemq.com", 1883, 60)

payload = {
    "weight": sensors["weight"],
    "temperature": sensors["temperature"],
    "moisture": sensors["moisture"],
    "r": r,
    "g": g,
    "b": b,
    "gas": sensors["gas"]
}

client.publish("iot/food/data", json.dumps(payload))
print("Data sent via MQTT")

import pandas as pd
import numpy as np
import base64, io
from PIL import Image

dataset = []

def extract_features(image):
    img_np = np.array(image)

    # Mean color
    r, g, b = np.mean(img_np[:,:,0]), np.mean(img_np[:,:,1]), np.mean(img_np[:,:,2])

    # Texture (variance)
    texture = np.var(img_np)

    return r, g, b, texture

label = "DAL"   # CHANGE for each food

image_data = capture_image()
img_bytes = base64.b64decode(image_data.split(',')[1])
image = Image.open(io.BytesIO(img_bytes))

r, g, b, texture = extract_features(image)

dataset.append([r, g, b, texture, label])
display(image)

df = pd.DataFrame(dataset, columns=["r","g","b","texture","label"])
df

df = pd.DataFrame(dataset, columns=["r","g","b","texture","label"])
df

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

X = df.drop("label", axis=1)
y = df["label"]

le = LabelEncoder()
y_enc = le.fit_transform(y)

model = RandomForestClassifier(n_estimators=300)
model.fit(X, y_enc)

def advanced_features(image):
    img = np.array(image)
    hist = cv2.calcHist([img],[0,1,2],None,[8,8,8],[0,256]*3)
    hist = hist.flatten()
    return hist

# Capture test image
image_data = capture_image()
img_bytes = base64.b64decode(image_data.split(',')[1])
image = Image.open(io.BytesIO(img_bytes))
display(image)

# Extract features
r, g, b, texture = extract_features(image)

# Prediction
pred = model.predict([[r, g, b, texture]])
conf = max(model.predict_proba([[r, g, b, texture]])[0]) * 100

food = le.inverse_transform(pred)[0]

# Output
print("🍛 Detected Food:", food)
print("📊 Confidence:", round(conf, 2), "%")
print("🔧 Sensors Used:")
print("   • Camera (Color Sensor - RGB)")
print("   • Camera (Texture Analysis)")

print("===================================")
print("🍛 IoT FOOD DETECTION RESULT")
print("===================================")
print("Detected Food   :", food)
print("Confidence      :", round(conf, 2), "%")
print("Sensors Used    :")
print(" - Camera (Color Sensor - RGB)")
print(" - Camera (Texture Analysis)")
print("===================================")

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

# Show image
plt.subplot(1,2,1)
plt.imshow(image)
plt.axis("off")
plt.title("Captured Food Image")

# Show confidence
plt.subplot(1,2,2)
plt.barh([food], [conf])
plt.xlim(0,100)
plt.xlabel("Confidence (%)")
plt.title("Detection Result")

plt.suptitle("🍛 IoT Food Detection Dashboard", fontsize=14)
plt.show()

print("🔧 Sensors Used:")
print("• Camera (Color Sensor - RGB)")
print("• Camera (Texture Analysis)")